{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-usearch
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - qiime2 {{ qiime2_epoch }}.*

test:
  requires:
    - coverage
    - pytest-cov
  imports:
    - q2_usearch
    - qiime2.plugins.usearch
  commands:
    - pytest --cov q2_usearch --pyargs q2_usearch

about:
  home: https://github.com/magicprotoss/q2-usearch
  license: BSD-3-Clause
  license_family: BSD
